### ISSUE TITLE
Connect to STM32F103 BluePhill 

### ISSUE THREAD

**Issue by EPBan** [khoih-prog/ESP8266_AT_WebServer#1]
I wanted to know if it is possible to connect an ESP826 module to the BluePhill STM32F103C board, through serial port 2, using this library.

**Comment by khoih-prog** [comment]
If I understand your question correctly:
1. Is it possible to connect ESP8266 AT-command shield to BluePill STM32F103C Serial Port 2?
2. Then is it possible for this library to run for that combination?

Answer:

1. I personally haven't tested that combination, but still think it's OK.
2. I guess if you can connect then run the AT command test OK, then the library will support. Currently there is a compile error, but it's an easy fix to support it in next release if you're still interested.

If you have any issue making the combined system working, it's better to ask or search other forums such as [STM32 forum](https://www.stm32duino.com/) or [ESP8266 forum](https://www.esp8266.com/)

**Comment by khoih-prog** [comment]
Version v1.0.3+ now supports STM32 boards, including STM32F103C.
