### ISSUE TITLE
ESP32_AT

### ISSUE THREAD

**Issue by tcpipchip** [khoih-prog/ESP8266_AT_WebServer#2]
works too!
![image](https://user-images.githubusercontent.com/11488460/84951310-a36c0500-b0c6-11ea-8804-a7f2e8766030.png)

**Comment by tcpipchip** [comment]
![image](https://user-images.githubusercontent.com/11488460/84951337-abc44000-b0c6-11ea-9b8c-679d99be8942.png)

**Comment by khoih-prog** [comment]
@tcpipchip 

Thanks for the update.

Could you please help add more info on how you achieve the good result so that many other people can follow and apply:

1. How to update the normal ESP32 to use AT-command?
2. Which is and where to download the working ESP32-AT firmware?
3. Are you using [PROTEUS Visual Designer](https://www.labcenter.com/) to simulate the Mega-2560 and ESP32-AT shield?
4. Did you test OK with real Mega-2560 + ESP32-AT shield?

Thanks,

**Comment by tcpipchip** [comment]
https://github.com/espressif/esp-at

https://github.com/espressif/esp-at/blob/master/docs/en/get-started/ESP_AT_Get_Started.md

```
sudo apt-get update
reboot
sudo apt install python-pip
pip install pyyaml xlrd
sudo apt install git

git clone --recursive https://github.com/espressif/esp-at.git
cd esp-at

make  ←esp-idf will be installed inside esp-at folder
```
you will get python requirements error

execute
```
/usr/bin/python -m pip install --user -r ./esp-idf/requirements.txt
```
execute
```
make clean
```
then
```
make
```
it will ask to xtensa gcc

inside the esp-at/esp-idf execute

```
cd esp-idf
./install.sh
```

wait!!!! long time

```
Installing ESP-IDF tools
Installing tools: xtensa-esp32-elf, esp32ulp-elf, openocd-esp32
Installing xtensa-esp32-elf@esp-2019r2-8.2.0
...
All done! You can now run:

  . ./export.sh

```

after all install, see the suggestion to point to ESP-IDF tools

```
. ./export.sh
```

it will ask to compile with idf.py build

but, use make

goto to esp-at

and 

```
cd ..
make clean
make
```
if ask to insall yaml

```
pip install PyYAML
```
then
```
make
```

```
CC build/app_trace/app_trace_util.o
CC build/app_trace/host_file_io.o
CC build/app_trace/app_trace.o
CC build/app_trace/heap_trace_tohost.o
CC build/app_trace/gcov/gcov_rtio.
.
.
.
Generating esp32.project.ld
LD build/esp-at.elf
esptool.py v2.8
CC phy_init_data.o
BIN phy_init_data.bin
To flash all build output, run 'make flash' or:
python /home/osboxes/esp-at/esp-idf/components/esptool_py/esptool/esptool.py --chip esp32 --port /dev/ttyUSB0 --baud 115200 --before default_reset --after hard_reset write_flash -z --flash_mode dio --flash_freq 40m --flash_size detect 0x10000 /home/osboxes/esp-at/build/ota_data_initial.bin 0x1000 /home/osboxes/esp-at/build/bootloader/bootloader.bin 0x20000 /home/osboxes/esp-at/build/at_customize.bin 0xf000 /home/osboxes/esp-at/build/phy_init_data.bin 0x100000 /home/osboxes/esp-at/build/esp-at.bin 0x8000 /home/osboxes/esp-at/build/partitions_at.bin
```

**Congratulations**

use 
make menuconfig to change settings…ttyUSB for example use to program, partions, make monitor, etc

```
make flash
```
=======================

tomorrow i answer other questions!

**Comment by tcpipchip** [comment]
https://github.com/espressif/esp-at

https://github.com/espressif/esp-at/blob/master/docs/en/get-started/ESP_AT_Get_Started.md

cd ~
sudo apt-get update
reboot
sudo apt install python-pip
pip install pyyaml xlrd
sudo apt install git

git clone --recursive https://github.com/espressif/esp-at.git
cd esp-at

make  ←esp-idf will be installed inside esp-at folder

you will get python requirements error

execute
/usr/bin/python -m pip install --user -r /home/osboxes/esp-at/esp-idf/requirements.txt

execute
make clean

then
make

it will ask to xtensa gcc

inside the esp-at/esp-idf execute
./install.sh

wait!!!! long time

Installing ESP-IDF tools
Installing tools: xtensa-esp32-elf, esp32ulp-elf, openocd-esp32
Installing xtensa-esp32-elf@esp-2019r2-8.2.0
Downloading xtensa-esp32-elf-gcc8_2_0-esp-2019r2-linux-amd64.tar.gz to /home/osboxes/.espressif/dist/xtensa-esp32-elf-gcc8_2_0-esp-2019r2-linux-amd64.tar.gz.tmp

after all install, see the suggestion to point to ESP-IDF tools

. ./export.sh

it will ask to compile with idf.py to build

but, use make

goto to esp-idf

and 

make clean

make

if ask to insall yaml

pip install PyYAML

then

make again

CC build/app_trace/app_trace_util.o
CC build/app_trace/host_file_io.o
CC build/app_trace/app_trace.o
CC build/app_trace/heap_trace_tohost.o
CC build/app_trace/gcov/gcov_rtio.
.
.
.
Generating esp32.project.ld
LD build/esp-at.elf
esptool.py v2.8
CC phy_init_data.o
BIN phy_init_data.bin
To flash all build output, run 'make flash' or:
python /home/osboxes/esp-at/esp-idf/components/esptool_py/esptool/esptool.py --chip esp32 --port /dev/ttyUSB0 --baud 115200 --before default_reset --after hard_reset write_flash -z --flash_mode dio --flash_freq 40m --flash_size detect 0x10000 /home/osboxes/esp-at/build/ota_data_initial.bin 0x1000 /home/osboxes/esp-at/build/bootloader/bootloader.bin 0x20000 /home/osboxes/esp-at/build/at_customize.bin 0xf000 /home/osboxes/esp-at/build/phy_init_data.bin 0x100000 /home/osboxes/esp-at/build/esp-at.bin 0x8000 /home/osboxes/esp-at/build/partitions_at.bin
congratulations

Here are the builds
osboxes@osboxes:~/esp-at/build$ ls *.bin
at_customize.bin  esp-at.bin  ota_data_initial.bin  partitions_at.bin  phy_init_data.bin



0x10000 ota_data_initial.bin 
0x1000 bootloader.bin 
0x20000 at_customize.bin 
0xf000 phy_init_data.bin 
0x100000 esp-at.bin 
0x8000 partitions_at.bin

You can use late the flash tools to burn that bin files! 

use 
make menuconfig to change settings…ttyUSB for example use to program, partions, make monitor, etc, but you can use default settings for now

insert the ESP32 to the serial and give permissions

sudo chmod 777 /dev/ttyUSBx

make flash

connect your microcontroller to the following ESP32 gpios

GPIO16 is RXD 
GPIO17 is TXD
open a serial terminal
and reset the ESP32
you will see the message
Ready

**Comment by tcpipchip** [comment]
1) How to update the normal ESP32 to use AT-command?
2) Which is and where to download the working ESP32-AT firmware?

Here the PDF and BINs
https://furb-my.sharepoint.com/:f:/g/personal/maw_furb_br/EtF_zUldHc9Mh7qQlTaAtO4BCO9jiM3u11GnkOeaKxv1LA?e=1tRX4O

3) Are you using PROTEUS Visual Designer to simulate the Mega-2560 and ESP32-AT shield?
YES!

4) Did you test OK with real Mega-2560 + ESP32-AT shield?
I dont have the Mega, only Virtual

Next step is to test on NRF52XXXX

**Comment by tcpipchip** [comment]
With ESP32 at commands, we will have more AT options about SSL, that the ESP8266, for example
AT+CIPSTART=**"SSL"**,"xxxxxxxxxxxxxx-ats.iot.us-east-1.amazonaws.com",8443

Maybe we have to advice the ARDUINO that the AT COMMANDS are to the ESP32 and not ESP8266, then have the SSL option on ARDUINO program and them use the SSL on NRF52XXXX, right ?

For example, using at commands we will have SSL option, the remainder is equal! 

AT+CIPSTART="SSL","xxxxxxxxxxxxxx-ats.iot.us-east-1.amazonaws.com",8443
cert_len=1224
prvtkey_len=1679
ca_len=1188
ctx ok
CONNECT
OK

// Update thing "lnu_001" property "prop1" to value "12"
AT+CIPSEND=261

OK

> POST /things/lnu_001/shadow HTTP/1.1
Host: xxxxxxxxxxxxxx-ats.iot.us-east-1.amazonaws.com
Content-Type: application/json  
Content-Length: 109

{
    "state": {
        "desired": { "prop1":"12"
        },
        "reported": {
        }
    }
}
Recv 261 bytes
id:0,Len:261,dp:0x3ffc3b98

SEND OK

+IPD,189:HTTP/1.1 200 OK
content-type: application/json
content-length: 157
date: Fri, 22 Feb 2019 13:45:11 GMT
x-amzn-RequestId: 09d6baa8-7cd9-24ff-cbef-654cbf95a59d
connection: keep-alive

+IPD,157:{"state":{"desired":{"prop1":"12"},"reported":{}},"metadata":{"desired":{"prop1":{"timestamp":1550843111}},"reported":{}},"version":7,"timestamp":1550843111}

**Comment by khoih-prog** [comment]
@tcpipchip 

Thanks for all the info. Will take some time for me to digest, then compile and test.

> With ESP32 at commands, we will have more AT options about SSL, that the ESP8266, for example
> AT+CIPSTART="SSL","xxxxxxxxxxxxxx-ats.iot.us-east-1.amazonaws.com",8443

This is a good point. It's almost not possible to use SSL on ESP8266-AT. 
Can you make an example to run SSL on ESP32, to connect to, for example., amazonaws. I'll test and post it on the repo examples.

One more question:

- How can you change the ESP32 AT-firmware back to the original ESP32 firmware? Or the BootLoader is just the same and we can **re-upload the new sketch** to erase the ESP32-AT firmware **similar to ESP8266**?

Regards,

**Comment by tcpipchip** [comment]
Thanks for all the info. Will take some time for me to digest, then compile and test.

**No problem!**

This is a good point. It's almost not possible to use SSL on ESP8266-AT.

**good**

Can you make an example to run SSL on ESP32, to connect to, for example., amazonaws. I'll test and post it on the repo examples.

**Yes, i can do that!** 

How can you change the ESP32 AT-firmware back to the original ESP32 firmware? Or the BootLoader is just the same and we can re-upload the new sketch to erase the ESP32-AT firmware similar to ESP8266?

**just erase all and burn, looks that the bootloader are not the same!**

**Comment by tcpipchip** [comment]
Hi! :)

**Comment by tcpipchip** [comment]
All fine! 
Works very very nice!
Attached the bins to burn on esp32 using ESPTOOLS and pictures of tests
ESP32 acessing the MQTT server of Amazon using 3 certificates :) ca, private, public

We are near to offer the at command option with SSL :)

![image](https://user-images.githubusercontent.com/11488460/85043846-3b1f3100-b163-11ea-9453-def441cd4959.png)

https://furb-my.sharepoint.com/:u:/g/personal/maw_furb_br/ERh0GIlLNXFEglfjUSiC73wBzGNVXi2bsd29zPg-Ff3vtw?e=gAiXqM

**Comment by khoih-prog** [comment]
> https://furb-my.sharepoint.com/:u:/g/personal/maw_furb_br/ERh0GIlLNXFEglfjUSiC73wBzGNVXi2bsd29zPg-Ff3vtw?e=gAiXqM

Can you check why downloaded **bin.rar** and **zip** file can't be extracted.

![Selection_438](https://user-images.githubusercontent.com/57012152/85045106-884bd480-b15c-11ea-92ab-a58db790c0a4.png)

Downloading 14 individual files is OK, but data corrupted.

**Comment by tcpipchip** [comment]
wait

**Comment by tcpipchip** [comment]
https://1drv.ms/f/s!Ak_-1v7Ug-k28VWIFu77S7SRcypP

**Comment by khoih-prog** [comment]
It's extracted OK now. 
Thanks.

**Comment by khoih-prog** [comment]
It seems that ESP8266-AT can support SSL now if you're using large Normal AT firmware 1024+1024, not for ESP-01).

See [ESP8266_NONOS_SDK](https://github.com/espressif/ESP8266_NONOS_SDK/tree/master/bin/at)

> AT firmware becomes larger since it supports more functions. So, we provide two firmwares here:

> 1024+1024: Normal AT, which is compiled from ESP8266_NONOS_SDK/examples/at, and uses mbedTLS lib.
> 512+512: Nano AT, which is compiled from ESP8266_NONOS_SDK/examples/at_nano, and uses SSL lib that supports less cipher suites. It is suggested to use normal AT(1024+1024), if your flash size is 2MB or larger.

Could you please test on ESP8266 to see if connecting to SSL **amazonaws** is still OK, and how to upload SSL certificates? Is the process similar to ESP32-AT's ?

**Comment by tcpipchip** [comment]
Please,
Burn on esp32 and test! Attention to the gpios used to txd and rxd, ok ?
I used my certificates

Enviado do meu iPhone

Em 18 de jun de 2020, às 13:37, Khoi Hoang <notifications@github.com<mailto:notifications@github.com>> escreveu:


It seems that ESP8266-AT can support SSL now if you're using large Normal AT firmware 1024+1024, not for ESP-01).

See ESP8266_NONOS_SDK<https://github.com/espressif/ESP8266_NONOS_SDK/tree/master/bin/at>

AT firmware becomes larger since it supports more functions. So, we provide two firmwares here:

1024+1024: Normal AT, which is compiled from ESP8266_NONOS_SDK/examples/at, and uses mbedTLS lib.
512+512: Nano AT, which is compiled from ESP8266_NONOS_SDK/examples/at_nano, and uses SSL lib that supports less cipher suites. It is suggested to use normal AT(1024+1024), if your flash size is 2MB or larger.

Could you please test on ESP8266 to see if connecting to SSL amazonaws is still OK, and how to upload SSL certificates? Is the process similar to ESP32-AT's ?

**Comment by tcpipchip** [comment]
Yes, i was doing that! I need some pause to study with my son! I will be back soon! Yes, i see anywhere that accepts too! I will produce the bin and send you with certificates!

Enviado do meu iPhone

Em 18 de jun de 2020, às 13:37, Khoi Hoang <notifications@github.com<mailto:notifications@github.com>> escreveu:


It seems that ESP8266-AT can support SSL now if you're using large Normal AT firmware 1024+1024, not for ESP-01).

See ESP8266_NONOS_SDK<https://github.com/espressif/ESP8266_NONOS_SDK/tree/master/bin/at>

AT firmware becomes larger since it supports more functions. So, we provide two firmwares here:

1024+1024: Normal AT, which is compiled from ESP8266_NONOS_SDK/examples/at, and uses mbedTLS lib.
512+512: Nano AT, which is compiled from ESP8266_NONOS_SDK/examples/at_nano, and uses SSL lib that supports less cipher suites. It is suggested to use normal AT(1024+1024), if your flash size is 2MB or larger.

Could you please test on ESP8266 to see if connecting to SSL amazonaws is still OK, and how to upload SSL certificates? Is the process similar to ESP32-AT's ?

**Comment by tcpipchip** [comment]
I see, it will possible use too the ESP8266 to open SSL.

But i dont have here a esp8266 to test. I gave him to my student!

Can you test there is i send the bins ?

**Comment by tcpipchip** [comment]
when you make it work, i send you the bin and certificates of ESP8266. i compiled now!

**Comment by khoih-prog** [comment]
Just posted [ESP8266_AT_WebServer v1.0.7](https://github.com/khoih-prog/ESP8266_AT_WebServer/releases/tag/v1.0.7) to add support to ESP32-AT command shields.
