### ISSUE TITLE
functional-vlpp.h

### ISSUE THREAD

**Issue by ednieuw** [khoih-prog/ESP8266_AT_WebServer#4]
Great job and I was pleased to find it. 

I get an error when compiling in Arduino IDE 1,8.13 for board Arduino NANO 33 IoT

I installed the library and copied the  platform.txt file from:

```
c:\Users\ednie\Documents\Files\Arduino\libraries\ESP8266_AT_WebServer-master\Packages_Patches\arduino\hardware\samd\1.8.11\
```

To:

```
c:\Users\ednie\AppData\Local\Arduino15\packages\arduino\hardware\samd\1.8.11\
```

This is the error in the Arduino IDE:

```
--------------------------------------------------------
In file included from sketch\defines.h:318:0,
                 from C:\Users\ednie\Documents\Files\Arduino\libraries\ESP8266_AT_WebServer-master\examples\UdpNTPClient\UdpNTPClient.ino:36:
C:\Users\ednie\Documents\Files\Arduino\libraries\ESP8266_AT_WebServer-master\src/ESP8266_AT_WebServer.h:115:10: fatal error: functional-vlpp.h: No such file or directory
 #include <functional-vlpp.h>
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
exit status 1
Error compiling for board Arduino NANO 33 IoT.
------------------------------------------------------------
```

**Comment by khoih-prog** [comment]
As stated in the [Prerequisites](https://github.com/khoih-prog/ESP8266_AT_WebServer#prerequisites), you have to install this [`Functional-VLPP library v1.0.1+`](https://github.com/khoih-prog/functional-vlpp) to compile without error.

---

## Prerequisites

 1. [`Arduino IDE 1.8.13+` for Arduino](https://www.arduino.cc/en/Main/Software)
 ...
 5. [`Arduino SAMD core 1.8.11+`](https://www.arduino.cc/en/Guide/ArduinoM0) for SAMD ARM Cortex-M0+ boards  (Nano 33 IoT, etc.).
 ... 
10. [**`Functional-VLPP library v1.0.1+`**](https://github.com/khoih-prog/functional-vlpp) to use server's lambda function. To install. check [![arduino-library-badge](https://www.ardu-badge.com/badge/Functional-Vlpp.svg?)](https://www.ardu-badge.com/Functional-Vlpp)
 ...
---

**But are you sure you need this library? This is designed for boards using ESP8266-AT-command WiFi shield, while Nano-33-IoT already has built-in WiFi NINA.**

If so, the correct library to use is [**WiFiWebServer**](https://github.com/khoih-prog/WiFiWebServer).

You can also explore these WiFiNINA-related libraries

1. [**WiFiNINA_Generic**](https://github.com/khoih-prog/WiFiNINA_Generic)
2. [**WiFiManager_NINA_Lite**](https://github.com/khoih-prog/WiFiManager_NINA_Lite)

Good Luck,

**Comment by ednieuw** [comment]
I have a Kickstarter board "Pocketscreen" with a ATSAMD21G18A is the main Microcontroller with a ESP8266EX.
I want to get the time from an NTPserver. I hope you library can help me with that.
The pocketscreen software uses SerialUSB instead Serial1. 
I am now trying to find out the name of the Pocketscreen so I can add it to your library as a define. It seems now it acts like a ESP8266_AT_USE_SAMD

in defines.h of UdpNTPClient at line 96 I changed Serial1 to SerialUSB
#elif defined(ESP8266_AT_USE_SAMD)
  // For SAMD
  #define EspSerial SerialUSB    // Serial1

Cheers
Ed
