### ISSUE TITLE
maixduino 

### ISSUE THREAD

**Issue by reltkaine** [khoih-prog/ESP8266_AT_WebServer#6]
### Describe the bug
compile error... for maixduino using exaample webclient....

C:\Users\ruvic\AppData\Local\Arduino15\packages\Maixduino\hardware\k210\0.3.11/cores/arduino/Stream.h: In member function 'void ESP8266_AT_WebServer::handleClient()':
C:\Users\ruvic\AppData\Local\Arduino15\packages\Maixduino\hardware\k210\0.3.11/cores/arduino/Stream.h:49:7: error: '<anonymous>.Stream::_startMillis' may be used uninitialized in this function [-Werror=maybe-uninitialized]
 class Stream : public Print
       ^~~~~~
cc1plus.exe: some warnings being treated as errors

### Steps to Reproduce

Steps to reproduce the behavior. Including the [MRE](https://stackoverflow.com/help/minimal-reproducible-example) sketches

### Information

Please ensure to specify the following:

* Arduino IDE version (e.g. 1.8.13) or Platform.io version
* `ESP8266`,`ESP32` or `STM32` Core Version (e.g. ESP8266 core v2.7.4, ESP32 v1.0.5 or STM32 v1.9.0)
* Contextual information (e.g. what you were trying to achieve)
* Simplest possible steps to reproduce
* Anything that might be relevant in your opinion, such as:
  * Operating system (Windows, Ubuntu, etc.) and the output of `uname -a`
  * Network configuration
  
### Example

```
Arduino IDE version: 1.8.13
ESP32 Core Version 1.0.5
OS: Ubuntu 20.04 LTS
Linux xy-Inspiron-3593 5.4.0-66-generic #74-Ubuntu SMP Wed Jan 27 22:54:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Context:
I encountered an endless loop while trying to connect to Local WiFi.

Steps to reproduce:
1. ...
2. ...
3. ...
4. ...
```

**Comment by khoih-prog** [comment]
This is a bug of recent [**Maixduino** core](https://github.com/sipeed/Maixduino).

Please copy [**Stream.h**](https://github.com/khoih-prog/ESP8266_AT_WebServer/blob/master/Packages_Patches/Maixduino/hardware/k210/0.3.11/cores/arduino/Stream.h) to replace [**Stream.h**](https://github.com/sipeed/Maixduino/blob/master/cores/arduino/Stream.h) of the core, for Windows machines, at 

```
C:\Users\ruvic\AppData\Local\Arduino15\packages\Maixduino\hardware\k210\0.3.11/cores/arduino/Stream.h
```

I'll add specific instructions for Maixduino into new release.

Good Luck,

**Comment by khoih-prog** [comment]
Hi @reltkaine 

The new release [**ESP8266_AT_WebServer** releases v1.4.1](https://github.com/khoih-prog/ESP8266_AT_WebServer/releases/tag/v1.4.1) has just been published to fix the compile error you reported.

Your contribution has been noted in [**Contributions and Thanks**](https://github.com/khoih-prog/ESP8266_AT_WebServer#contributions-and-thanks)

Be sure 

1. to follow the instructions in [Packages_Patches for Sipeed Maixduino boards](https://github.com/khoih-prog/ESP8266_AT_WebServer#10-For-Sipeed-Maixduino-boards) to update the core.
2. to check and/or update the ESP32-AT firmware to make it compatible with the library.

---

### Releases v1.4.1

1. Add instructions for SIPEED_MAIX_DUINO
2. Add SIPEED_MAIX_DUINO and update remaining `Packages' Patches`)
